In [2]:
import numpy as np
from tqdm import tqdm

## Numpy

행렬이나 다차원 배열을 쉽게 처리할 수 있도록 도와주는 python 라이브러리

<br>

- Numpy 특징 <br>
    - python list에 비해 빠르며 효율적인 메모리
    - 반복문 없이 배열에 대한 처리 
    - 다양한 기능 탑재
<br>
<br>

- Numpy 기능 <br>
1. shape: numpy dimension
2. ndim: shape에서 얼마나 나오는지
3. dtype: numpy 원소의 data type


#### median

축별 중앙값 산출

axis=0: 각 열(column)별로 중앙값 계산 <br>
axis=1: 각 행(row)별로 중앙값 계산

In [15]:
x = np.arange(12).reshape(4, 3)
print(x)

print('-' * 30)

print(np.median(x, axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------
[ 1.  4.  7. 10.]


In [16]:
x = np.random.randint(0, 10, (2, 5))
print(x)

print('-' * 30)

print(np.median(x, axis = 1))

[[6 0 0 8 2]
 [2 1 9 2 9]]
------------------------------
[2. 2.]


#### average

축별 가중합 산출

<br>
배열의 각 요소에 지정된 "가중치"를 곱한 후 그 합을 가중치의 합으로 나누어 가중 평균 산출

In [26]:
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])

3.7

#### mean

축별 평균 산출


In [29]:
x = np.arange(12).reshape(4, 3)
x.mean(axis =1)

array([ 1.,  4.,  7., 10.])

In [30]:
x = np.arange(12).reshape(4, 3)
print(x)

print('-' * 30)

print(x.mean(axis = 0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------
[4.5 5.5 6.5]


### 랜덤 배열 생성

- random: 균등분포에서 입력한 차원 만큼 데이터 생성 -> 실수

- randint: 지정한 범위 내에서 임의의 수 생성 -> 정수

In [4]:
np.random.random(size=(2, 3))

array([[0.87625725, 0.57557234, 0.16394683],
       [0.20972931, 0.25034458, 0.10182282]])

In [5]:
np.random.randint(0, 10, size=(5, 4))

array([[4, 2, 5, 0],
       [3, 7, 8, 0],
       [1, 2, 9, 4],
       [3, 4, 9, 7],
       [9, 6, 0, 9]])

- normal
    - 정규 분포에서 입력한 차원 만큼 데이터 생성
- randn
    - 표준정규분포에서 입력한 차원 만큼 데이터 생성
    - 표준정규분포: 평균 0, 표준편차 1

In [7]:
# loc: 평균, scale: 분산, size:dim
np.random.normal(loc = 10, scale = 5, size=(3, 2))

array([[ 6.61208877, 19.85208009],
       [15.04415091, 11.99831204],
       [ 2.57484956,  7.25714995]])

In [10]:
np.random.randn(2, 3)

array([[-1.96461188,  0.89401317, -1.463116  ],
       [-1.25413464, -0.14024344,  0.87375088]])

## 배열 조작

### 배열결합
- concatenate / reshape

### 배열 분할
- array_split

In [16]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)

print(np.concatenate([a, b], axis =1))

--------------------------------------------------
[[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]]


In [19]:
print(np.concatenate([a, b], axis =0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [22]:
x = np.arange(12)
print(np.split(x, 3)) # 배열 x를 3개의 균등한 크기의 부분 배열로 나눔 -> 각 부분 배열은 4개의 원소 가짐

print('-' * 50)

y = np.arange(12)
print(np.split(y, [2, 5, 8, 11])) # 주어진 인덱스 위치에서 분할

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
--------------------------------------------------
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10]), array([11])]


### 차원 변경
- reshape
    - 배열의 모양을 원하는 형태로 바꿈
    - 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함
- flattten
    - 배열을 1차원 배열로 바꿈


In [25]:
print(np.arange(6).reshape(3, 2))

print('-' * 50)

print(np.arange(12).reshape(2, 3, 2))

[[0 1]
 [2 3]
 [4 5]]
--------------------------------------------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
x = np.arange(12).reshape(2, 3, 2)